export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
}

export const userConstants = {
    GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',
    ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_SUCCESS',
    RESET_USER_ADDRESS: 'RESET_USER_ADDRESS',
    ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_FAILURE',
    GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_FAILURE: 'GET_USER_ORDER_FAILURE',
    GET_USER_ORDER_DETAILS_REQUEST: 'GET_USER_ORDER_DETAILS_REQUEST',
    GET_USER_ORDER_DETAILS_SUCCESS: 'GET_USER_ORDER_DETAILS_SUCCESS',
    GET_USER_ORDER_DETAILS_FAILURE: 'GET_USER_ORDER_DETAILS_FAILURE',
}

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE'
}


export const productConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST: 'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_SUCCESS: 'GET_PRODUCT_BY_SLUG_SUCCESS',
    GET_PRODUCT_BY_SLUG_FAILURE: 'GET_PRODUCT_BY_SLUG_FAILURE',
    GET_PRODUCT_BY_PAGE_REQUEST: 'GET_PRODUCT_BY_PAGE_REQUEST',
    GET_PRODUCT_BY_PAGE_SUCCESS: 'GET_PRODUCT_BY_PAGE_SUCCESS',
    GET_PRODUCT_BY_PAGE_FAILURE: 'GET_PRODUCT_BY_PAGE_FAILURE',
    GET_PRODUCT_DETAIL_BY_ID_REQUEST: 'GET_PRODUCT_DETAIL_BY_ID_REQUEST',
    GET_PRODUCT_DETAIL_BY_ID_SUCCESS: 'GET_PRODUCT_DETAIL_BY_ID_SUCCESS',
    GET_PRODUCT_DETAIL_BY_ID_FAILURE: 'GET_PRODUCT_DETAIL_BY_ID_FAILURE',
}

export const cartConstants = {
    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    GET_ALL_CART_REQUEST: 'GET_ALL_CART_REQUEST',
    GET_ALL_CART_FAILURE: 'GET_ALL_CART_FAILURE',
    GET_ALL_CART_SUCCESS: 'GET_ALL_CART_SUCCESS',
    UPDATE_CART_REQUEST: 'UPDATE_CART_REQUEST',
    UPDATE_CART_FAILURE: 'UPDATE_CART_FAILURE',
    UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
    RESET_CART: 'RESET_CART',
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
}

